defmodule Viable.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:systems), :type, to: :level
  end

  def down do
    rename table(:systems), :level, to: :type
  end
end